name: Build README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
          architecture: x64
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update README
        run: |-
          python build_readme.py
      - name: Commit and push if changed
        run: |-
          echo "Updating README"
          git checkout main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "tadod[bot]"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README.md"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
