name: Build README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
          architecture: x64
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update README
        run: |-
          python build_readme.py
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email 'readme-bot@tadod.com'
          git config --global user.name 'README-Bot'
          git add .
          git commit -m 'Update README' || exit 0
          git push
